### ISSUE TITLE
Blender File Export

### ISSUE THREAD

**Issue by bocklighting** [bocklighting/blenderengine#1]

**Comment by lukman06** [comment]
The blend file will be uploaded to s3 ?

**Comment by bocklighting** [comment]
I think that makes most sense. I have updated 1st JSON to include a blender boolean. Having true will export the blender and the image. I think there should be seperate folders on S3 for each type and the template files. Currently it goes into the same website/blender file. See more comments at #3 

[sample_json.json.zip](https://github.com/bocklighting/blenderengine/files/4177126/sample_json.json.zip)

**Comment by lukman06** [comment]
Alright got it

**Comment by lukman06** [comment]
Done #3
