### ISSUE TITLE
Update JSON

### ISSUE THREAD

**Issue by bocklighting** [bocklighting/blenderengine#3]
Hi Lukman, I think it makes sense to maybe move the callback into the first JSON file so that the JSON with the GLBs can be used easily multiple times. Also would make sense to have the images stored on S3 and then the callback would be the public url location on where to retrieve the file, instead of the current of sending file back to callback. What are your thoughts on this? I have placed a sample here.
[sample_json.json.zip](https://github.com/bocklighting/blenderengine/files/4177120/sample_json.json.zip)

callback: would send the file location in a JSON like {"image":"https://bockpublic0.s3.us-east-2.amazonaws.com/website/blender/U045MTAtZUcyLWlHMSAvIE1FRDUgLyBHTjI0RC1HOA-Side.png","blendfile":"https://bockpublic0.s3.us-east-2.amazonaws.com/website/blender/U045MTAtZUcyLWlHMSAvIE1FRDUgLyBHTjI0RC1HOA-Side.blend","cameraview":"Side", "runtime":600000}

**Comment by lukman06** [comment]
Makes sense

**Comment by lukman06** [comment]
Updated here is the new postman file :

[bpyaws_lambdaNewJsonFormat.postman_collection.zip](https://github.com/bocklighting/blenderengine/files/4198714/bpyaws_lambdaNewJsonFormat.postman_collection.zip)
