### ISSUE TITLE
Images getting cut off

### ISSUE THREAD

**Issue by bocklighting** [bocklighting/blenderengine#5]
Camera views are having images cut off. Can it be centered and size reduced to fit in image.

![QUcxNi1lRzgtaUcxIC8gTUVENSAvIDQxIC8gMzFEQ0ctRzggLyBHTjE3QS1HOA (3)](https://user-images.githubusercontent.com/31935831/74107750-40c79300-4b41-11ea-9437-8b89cd5ee287.png)
![QUcxNi1lRzgtaUcxIC8gTUVENSAvIDQxIC8gMzFEQ0ctRzggLyBHTjE3QS1HOA (2)](https://user-images.githubusercontent.com/31935831/74107755-4ae99180-4b41-11ea-9ba7-49f182d560dd.png)
![QUcxNi1lRzgtaUcxIC8gTUVENSAvIDQxIC8gMzFEQ0ctRzggLyBHTjE3QS1HOA (1)](https://user-images.githubusercontent.com/31935831/74107760-51780900-4b41-11ea-9156-ab44b959f97f.png)

**Comment by lukman06** [comment]
Alright will need to get the biggest model that you have there and we will try to fit it in the view

**Comment by bocklighting** [comment]
this would be the tallest view - https://bockpublic0.s3.us-east-2.amazonaws.com/website/BlenderJSONJob/OTI0REwtZUcwLWlHMSAvIExWRVYxLTMwMDAtWFhLIC8gNEdSMjQtRzAgLyBCQ0M2Uy0zLzQtRzAgLyBTVDMtOTYtRzA-6156211706731-Side.json

**Comment by bocklighting** [comment]
Found this - https://blender.stackexchange.com/questions/51563/how-to-automatically-fit-the-camera-to-objects-in-the-view

**Comment by lukman06** [comment]
Yeah that is possible too but it might not work in headless mode but will check it out
